matches:

  - regex: ";;bash (?P<shcmd>.*);;"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo $ESPANSO_SHCMD | /bin/bash"

  - trigger: ";bashit"
    replace: "{{completion}}"
    vars:
    - name: bashit-form
      type: form
      params:
        layout: |
          Prompt:
          [[prompt]]
          Describe the bash command you want to enter.
        fields:
          prompt:
            multiline: true

  - name: completion
    type: shell
    params:
      cmd: |
        ollama run llama3.1:8b 'I forget how to compose a bash command I want to enter into the CLI. I am going to describe it. Only respond to me with the full command, as if you were entering it in a terminal. Do not include the terminal cursor. Here is my description of the bash command: {{prompt.prompt}}'
